filter:
  excluded_paths:
    - 'tests/*'

build:
  environment:
    php: 7.3
  tests:
    override:
      - true
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run
          - phpcs-run

tools:
  external_code_coverage:
    runs: 2          # Scrutinizer will wait for two code coverage submissions (unit and integration test suites)
    timeout: 2400    # Timeout in seconds.